core/urls.py
from django.conf.urls import url

from . import views

app_name = 'core'
urlpatterns = [
	url(r'^$', views.index, name='index'),
]

hableituras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'', include('core.urls', namespace='core')),
    url(r'^sentdesc/', include('sentdesc.urls', namespace='sentdesc')),
	url(r'^planoleituras/', include('planoleituras.urls', namespace='planoleituras')),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
	url(r'^accounts/logout/$', auth_views.logout, {'next_page': 'sentdesc:index'}, name='logout'),
]

planoleituras/urls.py
from django.conf.urls import url

from . import views

app_name = 'planoleituras'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<tag_id>[0-9]+)/$', views.detalhe, name='detalhe'),
	url(r'^(?P<tag_id>[0-9]+)/atualizar$', views.atualizar, name='atualizar'),
]

planoleituras/models.py
from django.db import models

# Create your models here.
class Etiquetas(models.Model):
	etiqueta = models.CharField(max_length=20, unique=True)
	descritor = models.CharField(max_length=100)
	CTW = 'CTW'
	COW = 'COW'
	IGN = 'IGN'
	MSE = 'MSE'
	TIPO_CHOICES = (
        (CTW, 'Palavras de Conteúdo'),
        (COW, 'Palavras Comuns'),
		(MSE, 'Marcador de Sentença'),
		(IGN, 'Ignoradas'),
	)
	tipo_etiqueta = models.CharField(
		max_length=4,
		choices=TIPO_CHOICES,
		default=COW,
	)
	def __str__(self):
		return self.etiqueta + ' - ' + self.descritor
	class Meta:
		verbose_name = ("Etiqueta")
		verbose_name_plural = ("Etiquetas")
		
class Textos(models.Model):
	titulo = models.CharField(max_length=250)
	texto = models.TextField('Texto completo')
	origem = models.CharField(max_length=100)
	def __str__(self):
		return self.titulo + '(' + self.origem + ')'
	class Meta:
		verbose_name = ("Texto")
		verbose_name_plural = ("Textos")

class Dicionario(models.Model):
	etiqueta = models.ForeignKey(Etiquetas, 
		on_delete = models.SET_NULL,
		blank=True,
		null=True,
	)
	texto = models.ForeignKey(Textos, 
		on_delete = models.CASCADE
	) 
	palavra = models.CharField(max_length=50)
	correto = models.BooleanField(default=True)
	def __str__(self):
		return self.palavra #+ '(' + self.etiqueta + ')'
	class Meta:
		verbose_name = ("Palavra Etiqueta")
		verbose_name_plural = ("Palavras Etiquetadas")

class Sentencas(models.Model):
	texto = models.ForeignKey(Textos, 
		on_delete = models.CASCADE
	) 
	ordem = models.IntegerField(default=0)
	itens = models.CharField(
		max_length=250,
	)
	class Meta:
		verbose_name = ("Sentença")
		verbose_name_plural = ("Sentenças")

planoleituras/views.py
from django.shortcuts import  get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
import nltk, re
from pickle import load
from .models import Etiquetas, Textos, Dicionario, Sentencas
from django.db.models import Count

import json

# Create your views here.

def index(request):
	if request.POST:
		#processa o texto
		texto_etiquetado = {}
		etiquetas = Etiquetas.objects.all().order_by('etiqueta')
		texto = request.POST['texto']
		titulo = request.POST['titulo']
		origem = request.POST['origem']
		if origem == '':
			origem = 'Não definido'
		texto_bd = get_or_none(Textos, texto=texto)
		if not texto_bd:
			texto_bd = Textos(titulo = titulo, texto = texto, origem = origem)
			texto_bd.save()
			texto_id = texto_bd.id
			input = open('C:\\Users\\Tiago Gomes\\projects\\hableituras\\planoleituras\\t3_cut2.pkl', 'rb')
			tagger = load(input)
			input.close()
			texto = remover_caracteres_especiais(texto)
			tokens = nltk.word_tokenize(texto)
			texto_tagged = tagger.tag(tokens)
			tag_ignore = [',',':']
			tag_msentenca = ['.','!','?','...']
			sentenca = 1
			sentencas = {}
			itens_sentencas = []
			for word,tag in texto_tagged:
				tags = tag.split('|')
				correto = True
				for t in tags:
					if t != '+':
						if t in tag_ignore:
							t = 'IGN'
						if tag in tag_msentenca:
							t = 'PONT'
						if t == 'Não Encontrado':
							t = 'UNKN'
							palavra_existe = Dicionario.objects.select_related('etiqueta').filter(palavra=word).exclude(etiqueta__etiqueta='UNKN')
							if len(palavra_existe) > 0:
								t = palavra_existe[0].etiqueta.etiqueta
						etiqueta_f = etiquetas.filter(etiqueta=t)
						dicionario = Dicionario(etiqueta = etiqueta_f[0], texto = texto_bd, palavra = word, correto = correto)
						dicionario.save()
						itens_sentencas.append(dicionario.id)
						if etiqueta_f[0].tipo_etiqueta == 'MSE':
							sentencas[sentenca] = itens_sentencas
							itens_sentencas= []
							sentenca += 1
						texto_etiquetado[dicionario.id] = {'id_tag':dicionario.id, 
							'word':word, 
							'tag':etiqueta_f[0].etiqueta, 
							'tag_desc':etiqueta_f[0].descritor,
							'tipo_etiqueta':etiqueta_f[0].tipo_etiqueta}
			estatisticas_sentencas = gravar_sentencas(texto_id, sentencas)
		else:
			texto_id = texto_bd.id
			dicionario = Dicionario.objects.select_related('etiqueta').filter(texto=texto_id).order_by('id')
			for item in dicionario:
				if item.etiqueta.etiqueta == 'UNKN':
					palavra_existe = Dicionario.objects.select_related('etiqueta').filter(palavra=item.palavra).exclude(etiqueta__etiqueta='UNKN')
					if len(palavra_existe) > 0:
						t = palavra_existe[0].etiqueta
						item.etiqueta = t
						item.save()
				texto_etiquetado[item.id] = {'id_tag':item.id, 
					'word':item.palavra, 
					'tag':item.etiqueta.etiqueta,
					'tag_desc':item.etiqueta.descritor,
					'tipo_etiqueta':item.etiqueta.tipo_etiqueta}
			estatisticas_sentencas = get_estatisticas_sentenca(texto_id)
		print(estatisticas_sentencas)
		tag_list_c = get_tag_list(texto_id)
		estatisticas_texto = get_estatisticas_texto(texto_id)
		context = {'error_message': 'Texto Processado com Sucesso', #mensagem de conclusão do processo 
			'titulo': titulo, #Título do texto
			'total': estatisticas_texto['total'], #total de itens analisados
			'totalProc': estatisticas_texto['totalProc'], #total de itens taggeados
			'totalNProc': estatisticas_texto['totalNProc'], #total de itens ignorados
			'totalPCo': estatisticas_texto['totalPCo'], #total de palavras comuns
			'totalPCt': estatisticas_texto['totalPCt'], #total de palavras de conteúdo
			'totalIgn': estatisticas_texto['totalIgn'], #total de itens ignorados
			'etiquetas': get_etiquetas(), #lista de etiquetas (tags) para o select de edição
			'texto_etiquetado': texto_etiquetado, #texto completo com as tags
			'texto_id': texto_id, #id do texto analisado, após gravação no BD
			'tag_list_c': tag_list_c, #lista de tags e totais por tag para o dicionario de tags
			'estatisticas_sentencas': estatisticas_sentencas, #estatisticas gerais das sentenças que compõem o texto
		}
	else:
		#mostra o form normal
		context = {'error_message': 'Insira o texto a ser processado',}
	
	return render(request, 'planoleituras/index.html', context)

def detalhe(request, tag_id):
	#sent_desc = get_object_or_404(Habilidades_Leitura, pk=sent_desc_id)
	#atributos = Atributos_Habilidades.objects.select_related('atributo').filter(habilidades=sent_desc_id)
	#elementos_texto = Elementos_Texto.objects.all()
	context = {
		'etiquetas': get_etiquetas(),
		'tag_id': tag_id,
		'tag_atual': 'PROPESS',
	}
	return render(request, 'planoleituras/form_editar.html', context)

def atualizar(request, tag_id):
	if request.method == 'POST':
		tag_atual = request.POST['tag_atual']
		tag_nova = request.POST['tag_nova']
		todas = request.POST['todas']
		texto_id = request.POST['texto_id']
		context = {}
		if tag_atual != tag_nova:
			dicionario = get_object_or_404(Dicionario, pk=tag_id)
			palavra = dicionario.palavra
			list_id = ''
			etiqueta = get_object_or_404(Etiquetas, etiqueta=tag_nova)
			if todas == '1':
				dicionario = Dicionario.objects.select_related('etiqueta').filter(palavra=palavra).filter(texto=texto_id).order_by('id')
				for item in dicionario:
					item.etiqueta = etiqueta
					item.correto = False
					list_id = list_id + str(item.id) + '|'
					item.save()
			else:
				dicionario = get_object_or_404(Dicionario, pk=tag_id)
				dicionario.etiqueta = etiqueta
				dicionario.correto = False
				list_id = str(dicionario.id)
				dicionario.save()
			context['error_message'] = 'Item atualizado com sucesso'
		else:
			list_id = tag_id
			context['error_message'] = 'Item não alterado'
		estatisticas = get_estatisticas_texto(texto_id)
		estatisticas_sentencas = get_estatisticas_sentenca(texto_id)
		tag_list_c = get_tag_list(texto_id)
		context['tag_id'] = tag_id
		context['todas'] = todas
		context['tag_nova'] = tag_nova
		context['tag_atual'] = tag_atual
		context['tag_id_alterado'] = list_id
		context['total'] = estatisticas['total']
		context['totalProc'] = estatisticas['totalProc']
		context['totalIgn'] = estatisticas['totalIgn']
		context['totalPCt'] = estatisticas['totalPCt']
		context['totalPCo'] = estatisticas['totalPCo']
		context['totalNProc'] = estatisticas['totalNProc']
		context['tag_list_c'] = {}
		x = 0
		for descritor in sorted(tag_list_c):
			context['tag_list_c'][x] = str(tag_list_c[descritor]['etiqueta']) + ' - ' + str(tag_list_c[descritor]['descritor']) + ' (' + str(tag_list_c[descritor]['total']) + ') '
			x += 1
		context['estatisticas_sentencas'] = {}
		for item in sorted(estatisticas_sentencas):
			context['estatisticas_sentencas']['total_sent_'+str(item)] = str(estatisticas_sentencas[item]['total'])
			context['estatisticas_sentencas']['totalPCo_sent_'+str(item)] = str(estatisticas_sentencas[item]['totalPCo'])
			context['estatisticas_sentencas']['totalPCt_sent_'+str(item)] = str(estatisticas_sentencas[item]['totalPCt'])
		return HttpResponse(
			json.dumps(context),
			content_type="application/json"
		)

def get_etiquetas():
	etiquetas = Etiquetas.objects.all()
	context = {}
	for etiqueta in etiquetas:
		context[etiqueta.etiqueta] = etiqueta.descritor
	return context

def remover_caracteres_especiais(text):
	if isinstance(text, str):
		text = re.sub('\"', '', text)
		#text = re.sub('\n', '.\n', text)
		#text = text.replace('....','...')
		#text = text.replace('..','.')
		#text = text.replace('!.','!')
		#text = text.replace('?.','?')
		return text

def select_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None

def get_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None

def get_tag_list(texto_id):
	dicionario = Dicionario.objects.all().values('etiqueta__etiqueta', 'etiqueta__descritor').annotate(total=Count('palavra')).filter(texto=texto_id).exclude(etiqueta__etiqueta='UNKN').exclude(etiqueta__etiqueta='IGN').order_by('etiqueta__descritor')
	tag_list = {}
	for item in dicionario:
		tag_list[item['etiqueta__descritor']] = {}
		tag_list[item['etiqueta__descritor']]['etiqueta'] = item['etiqueta__etiqueta']
		tag_list[item['etiqueta__descritor']]['descritor'] = item['etiqueta__descritor']
		tag_list[item['etiqueta__descritor']]['total'] = item['total']
	return tag_list

def get_estatisticas_texto(texto_id):
	#texto = get_object_or_404(Textos, pk=texto_id)
	dicionario = Dicionario.objects.select_related('etiqueta').filter(texto=texto_id).order_by('id')
	estatisticas = {}
	estatisticas['total'] = str(len(dicionario))
	filtro = dicionario.exclude(etiqueta__etiqueta='UNKN')
	estatisticas['totalProc'] = str(len(filtro))
	filtro = dicionario.filter(etiqueta__tipo_etiqueta='IGN').exclude(etiqueta__etiqueta='UNKN')
	estatisticas['totalIgn'] = str(len(filtro))
	filtro = dicionario.filter(etiqueta__tipo_etiqueta='CTW')
	estatisticas['totalPCt'] = str(len(filtro))
	filtro = dicionario.filter(etiqueta__tipo_etiqueta='COW')
	estatisticas['totalPCo'] = str(len(filtro))
	totalNProc = str(int(estatisticas['total']) - int(estatisticas['totalProc']))
	estatisticas['totalNProc'] = totalNProc
	return estatisticas

def gravar_sentencas(texto_id, sentencas):
	texto = get_object_or_404(Textos, pk=texto_id)
	for x,y in sentencas.items():
		itens = str(y)
		itens = str(y).strip('[]')
		sentenca = Sentencas(texto = texto, ordem = x, itens = itens)
		sentenca.save()
	
	estatisticas_sentencas = get_estatisticas_sentenca(texto_id)
	return estatisticas_sentencas

def get_estatisticas_sentenca(texto_id):
	texto = get_object_or_404(Textos, pk=texto_id)
	sentencas = Sentencas.objects.select_related('texto').filter(texto=texto_id).order_by('ordem')
	estatisticas = {}
	for sentenca in sentencas:
		itens = sentenca.itens.split(', ')
		itens_int = []
		for i in itens: 
			itens_int.append(int(i))
		print()

planoleituras/templates/planoleituras/form_editar.html
{% load static %}
{% load planoleituras_extras %}
<script type='text/javascript'>
$(document).ready(function(){
// Define as variaveis de acordo com a quantidade da página // opcional.
	
	$(document).on('click', '.editable-cancel', function(){
		var id_tag = document.getElementById('tag_id').value;
		var tag_atual = document.getElementById('tag_atual').value;
		var url = document.getElementById('url').value;
		var link = '<a href="#" data-value="'+tag_atual+'" data-placeholder="" data-name="tag" data-url="'+url+'" data-pk="'+id_tag+'" data-type="select" class="tag_Editar" style="display: inline;">'+tag_atual+'</a>'
		$("#tag_" + id_tag).html(link);
		$("#tag_" + id_tag).removeClass('tag_' + id_tag + '_editando');
    });
	
	// Submit post on submit
	$('#post-form').on('submit', function(event){
		event.preventDefault();
		console.log("form submitted!")  // sanity check
		create_post();
	});
	
	//recuperando o csrf_token
	function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
	}
	var csrftoken = getCookie('csrftoken');
	
	//configurando o csrf_token no cabeçalho
	function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}
	$.ajaxSetup({
		beforeSend: function(xhr, settings) {
			if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
				xhr.setRequestHeader("X-CSRFToken", csrftoken);
			}
		}
	});
	
	// AJAX for posting
	function create_post() {
		console.log("create post is working!") // sanity check
		$.ajax({
			url : "{% url 'planoleituras:atualizar' tag_id %}", // the endpoint
			type : "POST", // http method
			data : { 
				'tag_id' : $("#tag_id").val(),
				'tag' : $("#tag").val(),
			}, // data sent with the post request

			// handle a successful response
			success : function(json) {
				console.log(json); // log the returned json to the console
				console.log("success"); // another sanity check
				for (x in json) {
					if (x != 'error_message' && x != 'sent_desc_id'){
						$("#"+x).html(json[x]);
					}
				}
				$('#form-conteudo').css("visibility", "hidden");
			},

			// handle a non-successful response
			error : function(xhr,errmsg,err) {
				$('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
					" <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
				console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
			}
		});
	};

});
</script>
<form action="{% url 'planoleituras:atualizar' tag_id %}" method="post" id="post_form">
	{% csrf_token %}
	<input type="hidden" name="tag_id" value='{{ tag_id }}' id="tag_id" />
	<input type="hidden" name="tag_atual" value='{{ tag_atual }}' id="tag_atual" />
	<input type="hidden" name="url" value='{% url "planoleituras:detalhe" tag_id %}' id="url" />
	<fieldset>
		<select id='tag' class='tag' required>
		{% if etiquetas %}
			{% for etiqueta, descritor in etiquetas.items|sort %}
				{% if etiqueta == tag_atual %}
					<option value='{{ etiqueta }}' selected >{{ descritor }}</option>
				{% else %}
					<option value='{{ etiqueta }}' >{{ descritor }}</option>
				{% endif %}
			{% endfor %}
		{% endif %}
		</select>
		<button type="button" class="btn btn-primary btn-sm editable-submit"><i class="glyphicon glyphicon-ok"></i></button>
		<button type="button" class="btn btn-default btn-sm editable-cancel"><i class="glyphicon glyphicon-remove"></i></button>
		<input type="checkbox" name="todas" value="1" checked></form>
	</fieldset>
</form>